name: Docker CI/CD validation

on:
  push:
    branches:
      - dev-roshan
  pull_request:
    branches:
      - dev-roshan
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG_LATEST: v1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app/imageswap
          push: true
          tags:  rosawant/base:imageswap-webhook-${{ env.DOCKER_TAG_LATEST }}
          file: ./app/imageswap/Dockerfile

