name: Docker CI/CD validation

on:
  push:
    branches:
      - dev-roshan
  pull_request:
    branches:
      - dev-roshan
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG_LATEST: ${{ github.job }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: imageswap-webhook-3
          path: app/imageswap/Dockerfile

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: imageswap-webhook-3